version: "3.9"

x-airflow-env: &airflow-env
  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY:-insecure_secret}
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
  SUPABASE_URL: ${SUPABASE_URL}
  SUPABASE_SERVICE_ROLE: ${SUPABASE_SERVICE_ROLE}

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:2.14.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports: ["9200:9200"]
    restart: unless-stopped

  airflow:
    image: apache/airflow:2.9.1-python3.12
    
    build:
      context: .                # root of the repo
      dockerfile: services/airflow/Dockerfile
    depends_on: [redis, opensearch]
    ports: ["8080:8080"]
    volumes:
      - ./services/airflow/dags:/opt/airflow/dags
      - airflow-logs:/opt/airflow/logs
      - ./crawler:/opt/airflow/crawler 
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./variables.json:/opt/airflow/variables.json
    env_file: .env
    environment:
      # <<: *airflow-env
      PIP_ADDITIONAL_REQUIREMENTS: "supabase opensearch-py==2.5.0"
      AIRFLOW__WEBSERVER__AUTHENTICATE: "False"
      # AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.allow_all"
      # (Optional) let you browse the config page
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8080"
    command: >
      bash -c "airflow db upgrade &&
               airflow users create --username admin --password changeme --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
               airflow webserver --port 8080"
    restart: unless-stopped
  
  crawler:
    build: ./crawler
    env_file: .env
    depends_on: [redis]

volumes:
  airflow-logs: